fragment ArticlesPage on ArticleConnection {
  nodes {
    ...ArticleNodesField
  }

  pageInfo {
    endCursor
    hasNextPage
  }
}

fragment ArticleNodesField on Article {
  title
  bureaus {
    name
  }
  publishedAt
  updatedAt
}
