name: CI-Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Check build
        run: |
          docker pull "$CACHE_TAG" || true

          docker build .
