name: CI-Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Check build
        run: |
          docker pull "$CACHE_TAG" || true

          docker build .
          
  test-yarn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      - name: yarn install
        run: yarn
      
      - name: yarn tsc
        run: yarn tsc

      - name: yarn build
        run: yarn build
